### ISSUE TITLE
Compiler croaks if max/min interval is too wide

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#107]
I am encountering problems if the max/min interval is too wide. The interval limit appears to be different on different compilers, but for example `INT16_MIN+1` to `INT16MAX-1` is too wide on either of the compilers I have tried. It always fails starting at line 448:

```c++
  constexpr bool valid[sizeof...(I)] = {is_valid<E, value<E, Min, IsFlags>(I)>()...};
  constexpr std::size_t count = values_count(valid);

  if constexpr (count > 0) {
    E values[count] = {};
    for (std::size_t i = 0, v = 0; v < count; ++i) {
      if (valid[i]) {
        values[v++] = value<E, Min, IsFlags>(i);
      }
    }
```
I realize that a wide interval may quite inefficient for a compiler. It might be useful to put a warning in the Limitations section of the docs and suggest what a reasonable limit might be.

**Comment by Neargye** [comment]
Could you please show an example of errors?

**Comment by rpatters1** [comment]
This code fails as indicated on XCode 12.5 and Visual Studio 2019:

```c++
enum AAA {A=INT16_MIN+1, B=-10000, C=-1000, D=-100, E=-10, F=0, G=10, H=100, I=1000, J=10000, K=INT16_MAX-1};
namespace magic_enum::customize {
   template <>
   struct enum_range<AAA> {
      static constexpr int min = INT16_MIN+1; // Must be greater than `INT16_MIN`.
      static constexpr int max = INT16_MAX-1; // Must be less than `INT16_MAX`.
   };
} // namespace magic_enum

template<typename ENUM>
static void foo()
{
   constexpr std::size_t count = magic_enum::enum_count<ENUM>(); // Constexpr variable 'count' must be initialized by a constant expression
   constexpr auto& names = magic_enum::enum_names<ENUM>(); //No matching function for call to 'enum_names'
}

int code()
{
   foo<AAA>();
}
```
And line 448 in `magic_enum.hpp`:

```c++
constexpr bool valid[sizeof...(I)] = {is_valid<E, value<E, Min, IsFlags>(I)>()...}; \\Constexpr variable 'valid' must be initialized by a constant expression
```

Finally, as an aside, the limitation of *greater* than `INT16_MIN` and *less than* `INT16_MAX` seems arbitrary. Is there any reason they shouldn't be `>=` and `<=` respectively? I don't need this, but it seems like an odd restriction.

**Comment by Neargye** [comment]
`INT16_MIN` / `INT16_MAX` - this is not a compiler limitation, but a limitation of the internal library implementation.

**Comment by Neargye** [comment]
If you hit a message like this:
```
[...]
note: constexpr evaluation hit maximum step limit; possible infinite loop?
```
Change the limit for the number of constexpr evaluated:

* MSVC /constexpr:depthN, /constexpr:stepsN https://docs.microsoft.com/en-us/cpp/build/reference/constexpr-control-constexpr-evaluation
* Clang -fconstexpr-depth=N, -fconstexpr-steps=N https://clang.llvm.org/docs/UsersManual.html#controlling-implementation-limits
* GCC -fconstexpr-depth=N, -fconstexpr-loop-limit=N, -fconstexpr-ops-limit=N https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/C_002b_002b-Dialect-Options.html


From https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

**Comment by rpatters1** [comment]
I ran into this problem again today, and your comment is helpful to a degree. But if you have any suggestions for appropriate settings, that would be very helpful. I'm thinking order-of-magnitude suggestions. Like, if the enum spans 10,000 values, the depth should be no less than X and the steps no less than Y. (Or on the order of X and the order of Y.)

The Microsoft page doesn't offer any caveats as to the penalties for setting these ridiculously high. I was able to get my enum (that spans from 32 to 8192) to compile, but only after trying values until I got sick of it and put them at depth 10000 and steps 2000000. These are orders-of-magnitude more than the documented defaults. Do you know if there is a penalty for having them so high?

**Comment by WolleTD** [comment]
I got some `uint16_t` enums in a protocol implementation that I'd like to use `magic_enum` on for outputs instead of having hundreds of lines of switch/case-Blocks. It would be great to use this on large enums.

I haven't gotten into hacking the code, what's the reason for the `int16_t` limit anyway? The [commit message](https://github.com/Neargye/magic_enum/commit/370a1d523684532eb743ec78213fd323f4b011f3) changing it from `int` unfortunately doesn't explain.

**Comment by Neargye** [comment]
@WolleTD 
`uint16_t` - this is not a compiler limitation, but a limitation of the internal library implementation. These restrictions were made due to internal lib implementations, the library was designed for little enums.

The library does a full brute-force of all possible enumerations in the range, so if you brute-force over all `uint16_t`  range - ~65535*20+-5 instances of templates and checks of the enum value, I think this is too much.

**Comment by rpatters1** [comment]
Not to be contrary or anything, but there is no difference in number between `INT16_MIN - INT16_MAX` and `0 - UINT16_MAX`. They're both 65535 (minus a couple if you like).

**Comment by Neargye** [comment]
@rpatters1  65535*(20+-5) instances

**Comment by rpatters1** [comment]
My only point is that

```c++
65535 == INT16_MAX - INT16_MIN
65535 == UINT16_MAX - 0
```

It's the same number of possible instances feeding into your formula whether you use `int16_t` or `uint16_t`.

**Comment by Neargye** [comment]
yep, the library check all possible enum values, if the enum values ​​can be negative, then it will check them too

**Comment by rpatters1** [comment]
But `uint16_t` cannot be negative.

**Comment by rpatters1** [comment]
Just to be clear: I'm not the one advocating for `uint16_t`. In fact, I'm perfectly fine with how it is now. (And thank you, it's a life saver.)

**Comment by Neargye** [comment]
note, if we are talking about flags `{ flag = 1 << 1, flag2 = 1 << 2, flag3 = 1 << 3 }`, then it is worth using the api from the namespace magic_enum::falgs, there goes a check of all binary flags, and there is no size limit.

**Comment by WolleTD** [comment]
Well, I'm not really advocating for `uint16_t` either, I could just hack it for my use case. At this point I'm simply trying to understand more of the problem.
In my particular case, I wouldn't brute-force the whole `uint16_t`-range, but something like `0x8000` to `0x8400`, which is way less than the `(u)int16_t`-range, but outside of the `int16_t` hard-limit when trying to customize it.

Wouldn't it be sufficient to check the difference between `min` and `max` rather than their absolut values?

**Comment by Neargye** [comment]
hmm, yes, I understand what you mean, I'll see what can do

**Comment by Neargye** [comment]
Fix in master

**Comment by WolleTD** [comment]
Thanks, works as expected!
