### ISSUE TITLE
Compile errors on Clang 8.0.1

### ISSUE THREAD

**Issue by colinbasnettskyboxlabs** [Neargye/magic_enum#73]
Hi there. I am trying to compile for PS4, using Clang 8.0.1:

```
-- The CXX compiler identification is Clang 8.0.1
-- The C compiler identification is Clang 8.0.1
```

However, I run into these errors:
```
[...]\magic_enum.hpp(458,23): error : constexpr variable 'values_v<ColorType, false>' must be initialized by a constant expression
[...]\magic_enum.hpp(467,23): error : constexpr variable 'min_v<ColorType, false, std::underlying_type<ColorType>::type>' must be initialized by a constant expression
[...]\magic_enum.hpp(470,23): error : constexpr variable 'max_v<ColorType, false, std::underlying_type<ColorType>::type>' must be initialized by a constant expression
[...]\magic_enum.hpp(475,18): error : constexpr variable 'max' must be initialized by a constant expression
[...]\magic_enum.hpp(476,18): error : constexpr variable 'min' must be initialized by a constant expression
[...]\magic_enum.hpp(477,18): error : constexpr variable 'range_size' must be initialized by a constant expression
[...]\magic_enum.hpp(478,17): error : static_assert expression is not an integral constant expression
```

Any help with this would be appreciated. Thank you!

**Comment by Neargye** [comment]
Could you please show an example of enum and what functions you used?

**Comment by colinbasnettskyboxlabs** [comment]
I am only using `magic_enum::enum_name` on this enum:

```
enum class ItemStackRequestActionType : uint8_t {
	Take,
	Place,
	Swap,
	Drop,
	Destroy,
	Consume,
	Create,
	RoomSurfaceCombine,
	ObeliskTransaction,
	HarvestRock,
	MakeRecipe,
	MakeRecipeAuto,
	MakeCreative,
	MakeRecipeOptional,
	// Deprecated
	CraftNonImplemented_DEPRECATEDASKCMBAS,
	CraftResults_DEPRECATEDASKCMBAS,
#ifndef TEST_INFRASTRUCTURE_DISABLED
	Test
#endif
};
```

**Comment by colinbasnettskyboxlabs** [comment]
Why is this issue marked as invalid?

**Comment by Neargye** [comment]
This is how I mark problems that do not look like a bug, but as incorrect behavior of the compiler.
For example, a regular x64 build with a clang passes the tests, but the clang on ps4 behaves incorrectly.

**Comment by craigsteyn** [comment]
I looked into this a bit, I think have a solution. 
PS4's compiler is fine, the issue is that the stl implementation does not have all the `std::array` functions marked `constexpr`, which is unfortunate. 

I was able to work around the issue with two changes. `static_string` now stores a raw `char[N]` array rather than a `std::array<char, N>` . in this case `.data()` was the offending function.

The other workaround was with the filter -> map on valid enum values, `operator[]` was not marked constexpr, I didn't confirm if a raw array would work here, but instead I used stored the valid enum values in the type of a `std::tuple` and then convert the tuple to an array, its easier to just show the change.

https://github.com/craigsteyn/magic_enum/commit/fa5a5054e403708a72cf64be1f6072f34c951a98

**Comment by Neargye** [comment]
@craigsteyn  
Thanks for looking, unfortunately, I didn't have a ps4 for tests. Quite unexpected behavior, I'll think about how best to fix it

**Comment by Neargye** [comment]
@craigsteyn  @colinbasnettskyboxlabs  could you please test https://github.com/Neargye/magic_enum/tree/fix_73 ?

**Comment by craigsteyn** [comment]
I can confirm that fix works, before you merge it, let me run your tests to get better coverage, since I was only using `magic_enum::enum_name`

**Comment by craigsteyn** [comment]
Okay, I finally was able to hook up all your tests in to my testing framework and run them all. Seems like they all pass! I think this fix does resolve the issue! Thanks.

**Comment by Neargye** [comment]
@craigsteyn 
Thank you very much for your help and prototype. I ended up doing it on arrays because by measurements it takes a little less compilation time than tuples.
