### ISSUE TITLE
Does not support large constexpr values in enumerations unless first element is < 128?

### ISSUE THREAD

**Issue by dakka** [Neargye/magic_enum#85]
The following enumeration will not compile if using `magic_enum::enum_entries`

`enum x_status : int64_t
{
   x_ok = 256,
   x_encode_error = 70001,
   x_decode_error = 70002,
   x_exception = 70003,
   x_service_state_change = 70004
};
`

However, the following will:

`enum x_status : int64_t
{
   x_not_used = 0,
   x_ok = 70000,
   x_encode_error = 70001,
   x_decode_error = 70002,
   x_exception = 70003,
   x_service_state_change = 70004
};
`

**Comment by alexkaratarakis** [comment]
Check [this](https://github.com/Neargye/magic_enum/blob/8c130658e1759fe6968ad0541bf965441c313698/include/magic_enum.hpp#L119-L128) on how to define your own range. The default range is -128 to 128. Anything outside the defined range is invisible to `magic_enum`.

 `magic_enum` will cause a compile error if the enum has zero entries, which is the case in the first example, as all entries are invisible. The second example compiles because of the value 0. It is still not what you want though, as the only value `magic_enum` can see without customizing the range is the 0; the rest of the values are invisible.
